// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dis_data

import (
	"github.com/go-redis/redis/v7"
)

// Injectors from wire.go:

func NewDisKey(redisClient *redis.ClusterClient) *DisKey {
	disKey := &DisKey{
		RedisClient: redisClient,
	}
	return disKey
}

func newDisKey() *DisKey {
	clusterClient := newRedis()
	disKey := &DisKey{
		RedisClient: clusterClient,
	}
	return disKey
}
