// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package room

import (
	"github.com/go-redis/redis/v7"
)

// Injectors from wire.go:

func newTenantRoomUser() *TenantRoomUser {
	clusterClient := newRedis()
	tenantRoomUserMap := &TenantRoomUserMap{
		RedisClusterClient: clusterClient,
	}
	tenantRoomUserSortedSet := &TenantRoomUserSortedSet{
		RedisClient: clusterClient,
	}
	tenantRoomUser := &TenantRoomUser{
		RedisClient:             clusterClient,
		TenantRoomUserMap:       tenantRoomUserMap,
		TenantRoomUserSortedSet: tenantRoomUserSortedSet,
	}
	return tenantRoomUser
}

func NewTenantRoomUser(redisClient *redis.ClusterClient) *TenantRoomUser {
	tenantRoomUserMap := &TenantRoomUserMap{
		RedisClusterClient: redisClient,
	}
	tenantRoomUserSortedSet := &TenantRoomUserSortedSet{
		RedisClient: redisClient,
	}
	tenantRoomUser := &TenantRoomUser{
		RedisClient:             redisClient,
		TenantRoomUserMap:       tenantRoomUserMap,
		TenantRoomUserSortedSet: tenantRoomUserSortedSet,
	}
	return tenantRoomUser
}
